---
name: Unity tests

on:
  pull_request: {}
  # push: { branches: [main] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build OpenBrush.${{ matrix.extension }} for ${{ matrix.targetPlatform }} with ${{ matrix.vrsdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - targetPlatform: Android
            vrsdk: Oculus
            extension: apk
          - targetPlatform: StandaloneWindows64
            vrsdk: SteamVR
            extension: exe
          - targetPlatform: StandaloneWindows64
            vrsdk: Monoscopic
            extension: exe

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install Oculus unity package
        if: matrix.vrsdk == 'Oculus'
        run: |
          # version 23.1
          wget -q https://securecdn.oculus.com/binaries/download/?id=3884880558189851 -O package.tmp
          mkdir tmp
          tar -C tmp -xzf package.tmp
          find tmp -type f | xargs chmod a-x
          for pn in tmp/*/pathname; do
            id=${pn%/*}
            id=${id#*/}
            p=$(head -1 $pn)
            d=${p%/*}
            mkdir -p "tmp/$d"
            [ -f "tmp/$id/asset" ] && cp -v "tmp/$id/asset" "tmp/$p"
            cp "tmp/$id/asset.meta" "tmp/${p}.meta"
          done
          mkdir -p Assets/Oculus
          cp -R tmp/Assets/Oculus/VR Assets/Oculus/
          cp -R tmp/Assets/Oculus/Platform Assets/Oculus/
          rm -rf tmp package.tmp

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          # Adding the sha ensures that we always save it... but we'll load the 'latest' one
          key: Library-${{ matrix.targetPlatform }}-${{ matrix.vrsdk }}-${{ github.sha }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-${{ matrix.vrsdk }}-
            Library-${{ matrix.targetPlatform }}-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          unityVersion: 2019.4.18f1
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: '-btb-target ${{ matrix.targetPlatform }} -btb-display ${{ matrix.vrsdk }} -btb-out /github/workspace/build/${{ matrix.targetPlatform }}/OpenBrush.${{ matrix.extension }}'
          buildMethod: BuildTiltBrush.CommandLine

      # Build
      # (experiment; maybe this will help with the imports)
      - name: Rebuild project
        if: matrix.vrsdk == 'Oculus'
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          unityVersion: 2019.4.18f1
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: '-btb-target ${{ matrix.targetPlatform }} -btb-display ${{ matrix.vrsdk }} -btb-out /github/workspace/build/${{ matrix.targetPlatform }}/OpenBrush.${{ matrix.extension }}'
          buildMethod: BuildTiltBrush.CommandLine

      - name: Show local changes
        run: |
          echo "git status"
          git status
          echo "git diff"
          git diff
          echo "git status --ignored"
          git status --ignored
          echo "OVRBuildConfig.asset"
          [ -f Assets/Resources/OVRBuildConfig.asset ] && cat Assets/Resources/OVRBuildConfig.asset || true
          echo "OVRPlatformToolSettings.asset"
          [ -f Assets/Resources/OVRPlatformToolSettings.asset ] && cat Assets/Resources/OVRPlatformToolSettings.asset || true

      # Output
      - name: Upload build/
        uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}-${{ matrix.vrsdk }}
          path: build

      - name: Upload the full tree
        uses: actions/upload-artifact@v2
        if: false
        with:
          name: Tree-${{ matrix.targetPlatform }}-${{ matrix.vrsdk }}
          path: |
            .
            !Library
            !build
            !.git
